# Generated by Django 4.1.7 on 2023-02-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email_id', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=32)),
                ('message', models.CharField(max_length=3000)),
            ],
        ),
    ]
